steps:
# Build and deploy consent page app
# Build the container image 
- name: 'gcr.io/cloud-builders/docker'
  id: buildDemoClientApp
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ce-demo-client', '-f', 'apps/financroo-tpp/Dockerfile', '.']
  env:
      - "DOCKER_BUILDKIT=1"
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: pushContainerImageDemoClientApp
  args: ['push', 'gcr.io/$PROJECT_ID/ce-demo-client']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: deployDemoClientApp
  entrypoint: gcloud
  args: ['run', 'deploy', 'ce-demo-client', 
        '--region', '$LOCATION',
        '--image', 'gcr.io/$PROJECT_ID/ce-demo-client', 
        '--set-env-vars','ACP_URL=https://${_CE_ACP_HOSTNAME}', 
        '--set-env-vars','ACP_MTLS_URL=https://${_CE_ACP_MTLS_HOSTNAME}',
        '--set-env-vars','TENANT=${_CE_ACP_TENANT}', 
        '--set-env-vars','OPENBANKING_SERVER_ID=${_CE_ACP_WORKSPACE}', 
        '--set-env-vars','LOG_LEVEL=debug',
        '--set-env-vars','SPEC=cdr',
        '--set-env-vars','GIN_MODE=debug',
        '--set-env-vars','UI_URL=${_DEMO_CLIENT_APP_URL}',
        '--set-env-vars','ENABLE_TLS_SERVER=false',
        '--set-env-vars','BANK_URL=https://${_APIGEE_X_ENDPOINT}/ce',
        '--set-env-vars','CLIENT_ID=${_CE_ACP_TPP_CLIENT_ID}', 
        '--set-env-vars','DB_FILE=/tmp/my.db',
        '--set-env-vars','CERT_FILE=/certs/tpp_cert.pem',
        '--set-env-vars','KEY_FILE=/certs-keys/tpp_key.pem',
        '--set-env-vars','ROOT_CA=/ca/ca.pem',
        '--update-secrets','/certs/tpp_cert.pem=ce-tpp-cert:latest',
        '--update-secrets','/certs-keys/tpp_key.pem=ce-tpp-key:latest',
        '--update-secrets','/ca/ca.pem=ce-cert-auth:latest',
        '--allow-unauthenticated']

substitutions:
    # The following substitution variables have a default dummy value - Correct values needs to be passed when launching this build script
    _CE_ACP_HOSTNAME: dummyValue 
    _CE_ACP_MTLS_HOSTNAME: dummyValue
    _CE_ACP_TENANT: dummyValue
    _CE_ACP_WORKSPACE: dummyValue 
    _DEMO_CLIENT_APP_URL: dummyValue 
    _APIGEE_X_ENDPOINT: dummyValue 
    _CE_ACP_TPP_CLIENT_ID: dummyValue

timeout: 1200s

images:
- gcr.io/$PROJECT_ID/ce-demo-client